<?php
// 오버라이딩 시 자식 클래스에서 재정의 할 함수를 선언하면 된다.
// 부모 클래스의 함수에 접근 시 parent::함수 를 선언하면 된다.
class People
{
    protected $name;
    protected $age;

    function printPeople()
    {
        print $this->name . " / " . $this->age;
    }
}

class Student extends People
{
    private $studentId;

    function __construct($name, $age, $studentId)
    {
        parent::__construct($name, $age);
        $this->studentId = $studentId;
    }

    function printPeople()
    {
        parent::printPeople(); // TODO: Change the autogenerated stub
        print("asdfasdf");
    }
}

?>